// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBAexEwOOBUrjnMOW_UOQeR_ceC2MH1U',
    appId: '1:865028370216:web:831e15a9f0510943292a1d',
    messagingSenderId: '865028370216',
    projectId: 'flutter-notepad-41fb4',
    authDomain: 'flutter-notepad-41fb4.firebaseapp.com',
    storageBucket: 'flutter-notepad-41fb4.firebasestorage.app',
    measurementId: 'G-JWHF14878M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-gAwhn--cS-LnLscrGPJLeGwbm3Dz3Y',
    appId: '1:865028370216:android:da32d12cf33a8260292a1d',
    messagingSenderId: '865028370216',
    projectId: 'flutter-notepad-41fb4',
    storageBucket: 'flutter-notepad-41fb4.firebasestorage.app',
  );
}
